### ISSUE TITLE
AttributeError: 'module' object has no attribute 'simple_decoder_fn_train'

### ISSUE THREAD

**Issue by dhirajpatnaik16297** [codekansas/seqgan-text-tensorflow#2]
sir
as i am runnin train.py for lorem.txt i am getting the following error:

dkp@DKP:~/Desktop/seqgan-text-tensorflow-master$ python train.py
2017-07-07 19:36:22.088169: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-07 19:36:22.088208: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-07 19:36:22.088226: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-07 19:36:22.088239: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-07 19:36:22.088253: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "train.py", line 71, in <module>
    model.build()
  File "/home/dkp/Desktop/seqgan-text-tensorflow-master/model.py", line 457, in build
    g_classes, g_seq, teach_loss = self.build_generator()
  File "/home/dkp/Desktop/seqgan-text-tensorflow-master/model.py", line 239, in build_generator
    teacher_fn = tf.contrib.seq2seq.simple_decoder_fn_train(
AttributeError: 'module' object has no attribute 'simple_decoder_fn_train

**Comment by codekansas** [comment]
I believe your TensorFlow version is incorrect (these features were in contrib - please reference the `requirements.txt` file)

**Comment by dhirajpatnaik16297** [comment]
Sir
I have understood the problem but i am not able to find the name of the
same function neither in the new APIr1.2.0 nor in APIr1.1.0.
Please let me know the new name of
tf.contrib.seq2seq.simple_decoder_fn_train() in the new versions.
Thanks

**Comment by codekansas** [comment]
Look in `requirements.txt`: This implementation uses APIr1.0.1

**Comment by dhirajpatnaik16297** [comment]
Ok thank you very much for your help.
